name: restful_solid_bloc
description: "Hornet - An anime image gallery application with NSFW content."
publish_to: 'none'
version: 0.1.1
license: MIT

environment:
  sdk: ^3.6.1

dependencies:
  bloc: ^9.0.0
  share_plus: ^10.1.4
  cached_network_image: ^3.3.0
  flutter_file_downloader: ^2.0.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  go_router: ^14.8.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/logo/
